### ISSUE TITLE
Any Document OR Example

### ISSUE THREAD

**Issue by droplet-js** [Yeicor/traefikgothauth#11]

**Comment by Yeicor** [comment]
Not yet, I still have to set it up on my own server :sweat_smile: but it works.

You should follow the documentation of your wanted provider(s) to get the ClientKey and Secret parameters and set their RedirectURI to match perfectly your URL. Then you configure this plugin with your values and everything should work. For the name of your provider you can check [this list](https://github.com/Yeicor/traefikgothauth/blob/0ce8080073416febc9665b9f80123e1c5da60808/providers.go#L92).

```yaml
http:
    middlewares:
        my-traefikgothauth:
            plugin:
                traefikgothauth:
                    CookieSecret: ANY_SECRET
                    Providers:
                        - Name: discord
                          ClientKey: YOUR_CLIENT_ID
                          ClientSecret: YOUR_SECRET
                          RedirectURI: https://yourdomain.com/__goth/discord/
```

Remember that this plugin accepts any valid account and just publishes the account information as headers for the next middleware to handle. If you want to implement authorization, use something like the [check request headers plugin](https://plugins.traefik.io/plugins/628c9eda108ecc83915d7760/check-request-headers-plugin) to validate the user ID.
