### ISSUE TITLE
How to setup for wecom redirectURI

### ISSUE THREAD

**Issue by droplet-js** [Yeicor/traefikgothauth#25]
```yaml
  traefik:
    container_name: traefik
    image: ghcr.io/traefik/traefik:v3.2.3
    restart: unless-stopped
    hostname: traefik
    ports:
      - 80:80
      - 443:443
    extra_hosts:
      - host.docker.internal:host-gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_data:/etc/traefik/acme
      - geoipupdate_data:/usr/share/GeoIP
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    command:
      - "--global.sendanonymoususage=false"
      - "--global.checknewversion=false"
      - "--api=true"
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--api.debug=false"
      - "--log.level=INFO"
      - "--log.format=common"
      - "--accesslog=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=letsencrypt"
      - "--certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-traefik@traefik.com}"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme-v2.json"
      - "--certificatesresolvers.letsencrypt.acme.keyType=EC384"
      - "--certificatesresolvers.letsencrypt.acme.preferredChain=ISRG Root X1"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      # Middleware traefikgoth
      - "--experimental.plugins.traefikgoth.modulename=github.com/Yeicor/traefikgothauth"
      - "--experimental.plugins.traefikgoth.version=v0.4.10"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.gzip.compress=true"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      # Middlewares
      - "traefik.http.routers.traefik.middlewares=gzip@docker"

  whoami:
    container_name: whoami
    image: ghcr.io/traefik/whoami:v1.10.3
    restart: unless-stopped
    hostname: whoami
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TZ=${TIME_ZONE:-Asia/Shanghai}
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.whoami.loadbalancer.server.port=80"
      - "traefik.http.routers.whoami.service=whoami"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${SERVER_DOMAIN:-localhost}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      # Middleware: goth plugin + wecom
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.logLevel=debug"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.cookieSecret=goth"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.providers[0].name=wecom"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.providers[0].clientKey=${WECOM_CORP_ID?err}"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.providers[0].clientSecret=${WECOM_CORP_SECRET?err}"
      # - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.providers[0].redirectURI=https://whoami.${SERVER_DOMAIN:-localhost}/__goth/wecom/"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.providers[0].redirectURI=https://whoami.${SERVER_DOMAIN:-localhost}/auth/wecom/callback"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.providers[0].scopes=snsapi_base"
      - "traefik.http.middlewares.whoamiauth.plugin.traefikgoth.providers[0].custom.agentID=${WECOM_AGENT_ID?err}"
      # Middlewares
      - "traefik.http.routers.whoami.middlewares=geoip@docker,whoamiauth"
```

```
Failed to authenticate
```

```
[traefik-oidc] [DEBUG] 2025-01-06 20:58:38 +0800 | Completing authentication provider=wecom 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:38 +0800 | Not authenticated provider=wecom error=state token mismatch 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:38 +0800 | Authenticating provider=wecom 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:38 +0800 | Completing authentication provider=wecom 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:38 +0800 | Not authenticated provider=wecom error=state token mismatch 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:38 +0800 | Authenticating provider=wecom 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:46 +0800 | Completing authentication provider=wecom 
[traefik-oidc] [ERROR] 2025-01-06 20:58:47 +0800 | Failed to authenticate provider=wecom error=CODE: 41004, MSG: corpsecret missing, hint: [1736168327516412547228712], from ip: 120.26.100.26, more info at https://open.work.weixin.qq.com/devtool/query?e=41004 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:47 +0800 | Completing authentication provider=wecom 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:47 +0800 | Not authenticated provider=wecom error=state token mismatch 
[traefik-oidc] [DEBUG] 2025-01-06 20:58:47 +0800 | Authenticating provider=wecom 
```
